Feature: UAA authorization bearer token check

   check the UAA auth token

   Background: token generated by UAA
   Given a valid token is generated from UAA

   Scenario Outline: check for a appropriate authorization header in the request
   When a <method> request to  <api> contains auth headers with bearer token
   Then the API shouldn't return unauthorized status 

   Examples:
   |api|method|
|"https://evn-catalog-service-dev.run.aws-usw02-pr.ice.predix.io/v1/evn/catalog/coverages"|"GET"|
|"https://evn-catalog-service-dev.run.aws-usw02-pr.ice.predix.io/v1/evn/catalog/coverages/1"|"GET"|
|"https://evn-catalog-service-dev.run.aws-usw02-pr.ice.predix.io/v1/evn/catalog/coverages/assets?fuelId=1"|"GET"|

   